title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"
logo: "/logo.png"

dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
show_footer: true            # show the "previous" and "next" links at the end of each post
hide_title: false            # don't show the site title in the header
style: custom                # use a custom style

permalink: pretty            # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %-d, %Y"    # see http://shopify.github.io/liquid/filters/date/
paginate: 3                  # number of articles per page, use "layout: paginate" in the index.html to enable pagination

navigation:                  # site navigation in the header
  - index.html
  - categories.html
  - archive.html
  - README.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  search:   "/pages/search"
  envelope: "mailto:10193241+bahnfrei@users.noreply.github.com"
  github:   "https://github.com/bahnfrei/contrast"
  rss:      "/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
 - jekyll-paginate
 - jekyll-gist

include: ['pages']
