title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
logo: "/assets/images/logo.png"
permalink: pretty
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %-d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: false      # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: true            # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "categories.html", icon: th-list}
  - {file: "archive.html", icon: list}

external:                    # see http://fontawesome.com/icons
  - {title: Search, icon: search, file: "search.html"}
  - {title: Mail, icon: envelope, url: "mailto:mailto:10193241+bahnfrei@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/bahnfrei/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed

include: ['pages']

